
import React from 'react';

export const AGENT_COLORS = [
  { bg: 'bg-rose-500', text: 'text-white' },
  { bg: 'bg-sky-500', text: 'text-white' },
  { bg: 'bg-emerald-500', text: 'text-white' },
  { bg: 'bg-amber-500', text: 'text-white' },
  { bg: 'bg-violet-500', text: 'text-white' },
  { bg: 'bg-indigo-500', text: 'text-white' },
];

export const LANGUAGES = {
  zh: {
    title: "LG Subscribe Supreme",
    schedule: "排班表",
    docCenter: "管理 / 文檔",
    loginTitle: "系統安全登入",
    loginBtn: "進入系統",
    slot1: "早班 (10am-4pm)", 
    slot2: "晚班 (4pm-10pm)",
    weekdays: ["日", "一", "二", "三", "四", "五", "六"],
    memo: "重要公告 (Memo)",
    forms: "申請表格 (Forms)",
    upload: "發布文檔",
    generate: "AI 排班生成",
    deleteAgent: "刪除代理",
    confirmTitle: "操作確認",
    peakDay: "人流高峰",
    empty: "空缺",
    get: "獲取",
    adminConsole: "管理控制台",
    personalSettings: "個人可用性設定",
    markUnavail: "點擊標記不方便的時間",
    confirmBtn: "確認並執行",
    backBtn: "返回",
    leads: "顧客報備",
    leadProtection: "搶單防護系統",
    registerLead: "報備新顧客",
    customerName: "顧客稱呼",
    customerInfo: "辨識資訊 (如電話後4位)",
    productInterest: "意向產品 / 項目 (Mention Product)",
    visitLocation: "預計前往地點",
    visitDate: "預計日期",
    submitLead: "提交報備",
    leadHistory: "報備紀錄",
    protectionActive: "防護生效中",
    aiThinking: "正在分析報備紀錄、可用性及工作量。PT 限制已強制執行。",
    noLeads: "目前無報備紀錄",
    reportAgent: "報備代理",
    expectedVisit: "預計到訪",
    regDate: "登記日期 / 系統時間",
    quickGen: "快速生成",
    quickGenMsg: "根據基礎邏輯自動分配人手 (強制執行 PT 限制)。",
    aiGenMsg: "AI 將自動優化排班，確保人手充足並符合 PT 規定。",
    invalidLogin: "認證失敗：代碼無效",
    fillAllInfo: "請填寫完整資訊",
    confirmDeleteLead: "確定要取消此報備紀錄嗎？",
    leadSubmitted: "報備成功！",
    enterAgentName: "輸入代理姓名:",
    enterAgentCode: "輸入 Agent Code (M/F):",
    isPTConfirm: "是否為 Part-Time (PT) 員工？",
    confirmDeleteAgent: "確定要移除這位代理嗎？",
    status: "狀態",
    management: "管理",
    exportData: "匯出備份 (JSON)",
    importData: "還原備份",
    backupSuccess: "資料備份已下載",
    restoreSuccess: "資料還原成功！",
    restoreError: "還原失敗：檔案格式錯誤",
    availabilityMode: "可用性設定模式",
    selectUnavail: "標記不方便日期",
    selectAvail: "標記可上班日期",
    cloudSync: "雲端同步",
    syncKey: "同步密鑰 (自定義)",
    pushCloud: "上傳至雲端",
    pullCloud: "從雲端下載",
    syncSuccess: "同步成功！",
    syncError: "同步失敗，請檢查密鑰或網路",
    syncPlaceholder: "輸入您的私密同步代碼",
    syncWarning: "注意：下載雲端資料將覆蓋目前的本地排班資料。"
  },
  en: {
    title: "LG Subscribe Supreme",
    schedule: "Duty Roster",
    docCenter: "Docs / Account",
    loginTitle: "Secure Portal Login",
    loginBtn: "Enter System",
    slot1: "AM Shift (10am-4pm)", 
    slot2: "PM Shift (4pm-10pm)",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    memo: "Important Memos",
    forms: "Application Forms",
    upload: "Publish Doc",
    generate: "AI Auto-Duty",
    deleteAgent: "Remove Agent",
    confirmTitle: "Confirm Action",
    peakDay: "Peak Traffic",
    empty: "Vacant",
    get: "Get",
    adminConsole: "Admin Console",
    personalSettings: "My Availability",
    markUnavail: "Click to mark unavailable slots",
    confirmBtn: "Confirm & Execute",
    backBtn: "Back",
    leads: "Leads Protection",
    leadProtection: "Lead Anti-Theft System",
    registerLead: "Register New Lead",
    customerName: "Customer Name",
    customerInfo: "ID Info",
    productInterest: "Interested Product",
    visitLocation: "Target Location",
    visitDate: "Expected Date",
    submitLead: "Submit Lead",
    leadHistory: "Lead History",
    protectionActive: "Protection Active",
    aiThinking: "Analyzing data...",
    noLeads: "No lead records found",
    reportAgent: "Assigned Agent",
    expectedVisit: "Expected Visit",
    regDate: "Registered Date",
    quickGen: "Quick Gen",
    quickGenMsg: "Basic logic assignment.",
    aiGenMsg: "AI optimization with PT compliance.",
    invalidLogin: "Authentication Failed: Invalid Code",
    fillAllInfo: "Please fill in all info",
    confirmDeleteLead: "Cancel this lead?",
    leadSubmitted: "Lead registered!",
    enterAgentName: "Enter agent name:",
    enterAgentCode: "Enter Agent Code:",
    isPTConfirm: "Is this PT employee?",
    confirmDeleteAgent: "Remove this agent?",
    status: "Status",
    management: "Management",
    exportData: "Export Backup (JSON)",
    importData: "Restore Data",
    backupSuccess: "Backup downloaded",
    restoreSuccess: "Data restored successfully!",
    restoreError: "Restore failed: Invalid file",
    availabilityMode: "Availability Mode",
    selectUnavail: "Mark Unavailable",
    selectAvail: "Mark Available",
    cloudSync: "Cloud Sync",
    syncKey: "Sync Secret Key",
    pushCloud: "Push to Cloud",
    pullCloud: "Pull from Cloud",
    syncSuccess: "Synced successfully!",
    syncError: "Sync failed. Check key or network.",
    syncPlaceholder: "Enter your private sync code",
    syncWarning: "Warning: Pulling cloud data will overwrite your local duty roster."
  },
  ms: {
    title: "LG Subscribe Supreme",
    schedule: "Jadual Tugas",
    docCenter: "Dokumen / Akaun",
    loginTitle: "Log Masuk Selamat",
    loginBtn: "Masuk Sistem",
    slot1: "Syif Pagi", 
    slot2: "Syif Petang",
    weekdays: ["Ahad", "Isnin", "Selasa", "Rabu", "Khamis", "Jumaat", "Sabtu"],
    memo: "Hebahan Penting",
    forms: "Borang",
    upload: "Terbit Dokumen",
    generate: "Penjanan AI",
    deleteAgent: "Padam Ejen",
    confirmTitle: "Sahkan",
    peakDay: "Trafik Tinggi",
    empty: "Kosong",
    get: "Dapatkan",
    adminConsole: "Konsol Admin",
    personalSettings: "Ketersediaan Saya",
    markUnavail: "Klik untuk tidak tersedia",
    confirmBtn: "Sahkan",
    backBtn: "Kembali",
    leads: "Perlindungan Lead",
    leadProtection: "Anti-Curi Lead",
    registerLead: "Daftar Lead",
    customerName: "Nama Pelanggan",
    customerInfo: "ID Info",
    productInterest: "Produk",
    visitLocation: "Lokasi",
    visitDate: "Tarikh",
    submitLead: "Hantar",
    leadHistory: "Rekod",
    protectionActive: "Aktif",
    aiThinking: "Menganalisis...",
    noLeads: "Tiada rekod",
    reportAgent: "Ejen",
    expectedVisit: "Jangkaan",
    regDate: "Tarikh Daftar",
    quickGen: "Janana Cepat",
    quickGenMsg: "Tugas logik asas.",
    aiGenMsg: "AI mengoptimumkan jadual.",
    invalidLogin: "Gagal: Kod Tidak Sah",
    fillAllInfo: "Sila isi semua maklumat",
    confirmDeleteLead: "Batal lead ini?",
    leadSubmitted: "Berjaya!",
    enterAgentName: "Nama ejen:",
    enterAgentCode: "Kod ejen:",
    isPTConfirm: "Pekerja PT?",
    confirmDeleteAgent: "Padam ejen?",
    status: "Status",
    management: "Pengurusan",
    exportData: "Eksport Sandaran",
    importData: "Pulihkan Data",
    backupSuccess: "Sandaran dimuat turun",
    restoreSuccess: "Data berjaya dipulihkan!",
    restoreError: "Gagal: Fail tidak sah",
    availabilityMode: "Mod Ketersediaan",
    selectUnavail: "Tanda Tidak Tersedia",
    selectAvail: "Tanda Tersedia",
    cloudSync: "Awan Segerak",
    syncKey: "Kunci Rahsia",
    pushCloud: "Hantar ke Awan",
    pullCloud: "Ambil dari Awan",
    syncSuccess: "Berjaya segerak!",
    syncError: "Gagal segerak.",
    syncPlaceholder: "Masukkan kod segerak",
    syncWarning: "Amaran: Mengambil data awan akan menggantikan jadual tempatan anda."
  }
};

export const LG_MAROON = "#A50034";
