
import React from 'react';

export const AGENT_COLORS = [
  { bg: 'bg-rose-500', text: 'text-white' },
  { bg: 'bg-sky-500', text: 'text-white' },
  { bg: 'bg-emerald-500', text: 'text-white' },
  { bg: 'bg-amber-500', text: 'text-white' },
  { bg: 'bg-violet-500', text: 'text-white' },
  { bg: 'bg-indigo-500', text: 'text-white' },
];

export const LANGUAGES = {
  zh: {
    title: "LG Subscribe Supreme",
    partnerPortal: "夥伴門戶系統",
    supremeSystem: "SUPREME 管理系統",
    agentCodeLabel: "請輸入 Agent Code",
    schedule: "排班表",
    docCenter: "管理 / 文檔",
    loginTitle: "系統安全登入",
    loginBtn: "進入系統",
    slot1: "早班", 
    slot2: "晚班",
    weekdays: ["日", "一", "二", "三", "四", "五", "六"],
    memo: "重要公告 (Memo)",
    forms: "申請表格 (Forms)",
    upload: "發布文檔",
    generate: "AI 智能編排",
    deleteAgent: "刪除代理",
    confirmTitle: "操作確認",
    peakDay: "人流高峰",
    empty: "空缺",
    get: "獲取",
    adminConsole: "管理者 SUPREME",
    personalSettings: "個人可用性設定",
    markUnavail: "點擊標記不方便的時間",
    confirmBtn: "確認並執行",
    backBtn: "返回",
    leads: "顧客報備",
    leadProtection: "搶單防護系統",
    registerLead: "報備新顧客",
    customerName: "顧客稱呼",
    customerInfo: "辨識資訊",
    productInterest: "意向產品",
    visitLocation: "預計前往地點",
    visitDate: "預計日期",
    submitLead: "提交報備",
    leadHistory: "報備紀錄",
    protectionActive: "防護生效中",
    aiThinking: "正在分析數據...",
    noLeads: "目前無報備紀錄",
    reportAgent: "報備代理",
    expectedVisit: "預計到訪",
    regDate: "登記日期",
    quickGen: "快速生成",
    quickGenMsg: "基本分配邏輯。",
    aiGenMsg: "AI 優化排班。",
    invalidLogin: "認證失敗：代碼無效",
    fillAllInfo: "請填寫完整資訊",
    confirmDeleteLead: "確定要取消此報備嗎？",
    leadSubmitted: "報備成功！",
    enterAgentName: "輸入代理姓名:",
    enterAgentCode: "輸入 Agent Code:",
    isPTConfirm: "是否為 PT 夥伴？",
    confirmDeleteAgent: "確定要移除嗎？",
    status: "狀態",
    management: "管理夥伴",
    exportData: "匯出備份",
    importData: "還原備份",
    backupSuccess: "備份已下載",
    restoreSuccess: "還原成功！",
    restoreError: "格式錯誤",
    availabilityMode: "可用性設定",
    selectUnavail: "標記不方便",
    selectAvail: "標記可上班",
    cloudSync: "雲端同步",
    syncKey: "同步密鑰",
    pushCloud: "上傳至雲端",
    pullCloud: "從雲端下載",
    syncSuccess: "同步成功！",
    syncError: "同步失敗 (請檢查網絡或 API Key)",
    syncPlaceholder: "Agent Code",
    syncWarning: "將覆蓋本地排班資料。",
    supremeConsole: "SUPREME 工作台",
    publish: "公告排班表",
    retract: "撤回公告",
    pushToAll: "推送到所有人設備",
    saveMyTime: "確認並提交我的時間",
    syncDone: "同步完成！",
    syncDoneMsg: "SUPREME 與夥伴們都會看到最新的變動",
    supremeThinking: "SUPREME 正在智能排班...",
    pleaseFillAvail: "請填寫您的可用時間",
    waitingSupreme: "SUPREME 尚未發布最終排班表",
    finalizedMsg: "最終排班表已公告",
    finalizedSub: "請依照下方行程準時出勤",
    statusFinalized: "排班已公告",
    statusDraft: "等待公告中",
    vacant: "空缺",
    logoutConfirm: "確定登出？",
    syncingCloud: "實時數據對齊中...",
    syncingCloudSub: "LG Supreme 安全同步",
    addPartner: "新增夥伴",
    partnerList: "夥伴列表",
    submittedStatus: "已提交",
    pendingStatus: "填寫中",
    partnerName: "夥伴姓名",
    partnerCode: "Agent Code",
    resetStatus: "重置所有狀態",
    resetConfirm: "確定要清除所有人的「已提交」狀態嗎？(通常在換月時使用)",
    partnerAdded: "夥伴已新增",
    partnerDeleted: "夥伴已刪除"
  },
  en: {
    title: "LG Subscribe Supreme",
    partnerPortal: "Partner Portal",
    supremeSystem: "SUPREME Management System",
    agentCodeLabel: "Enter Agent Code",
    schedule: "Duty Roster",
    docCenter: "Docs / Account",
    loginTitle: "Secure Portal Login",
    loginBtn: "Enter System",
    slot1: "AM Shift", 
    slot2: "PM Shift",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    memo: "Memos",
    forms: "Forms",
    upload: "Publish Doc",
    generate: "AI Auto-Duty",
    deleteAgent: "Remove Agent",
    confirmTitle: "Confirm",
    peakDay: "Peak",
    empty: "Vacant",
    get: "Get",
    adminConsole: "Admin SUPREME",
    personalSettings: "My Availability",
    markUnavail: "Mark unavailable slots",
    confirmBtn: "Confirm",
    backBtn: "Back",
    leads: "Leads",
    leadProtection: "Lead Anti-Theft",
    registerLead: "New Lead",
    customerName: "Customer",
    customerInfo: "ID Info",
    productInterest: "Product",
    visitLocation: "Location",
    visitDate: "Date",
    submitLead: "Submit",
    leadHistory: "History",
    protectionActive: "Active",
    aiThinking: "Analyzing...",
    noLeads: "No leads",
    reportAgent: "Agent",
    expectedVisit: "Visit",
    regDate: "Registered",
    quickGen: "Quick",
    quickGenMsg: "Basic logic.",
    aiGenMsg: "AI optimization.",
    invalidLogin: "Login Failed: Invalid Code",
    fillAllInfo: "Fill all info",
    confirmDeleteLead: "Cancel lead?",
    leadSubmitted: "Registered!",
    enterAgentName: "Agent name:",
    enterAgentCode: "Agent Code:",
    isPTConfirm: "Is PT Partner?",
    confirmDeleteAgent: "Remove agent?",
    status: "Status",
    management: "Partners",
    exportData: "Export",
    importData: "Restore",
    backupSuccess: "Backup done",
    restoreSuccess: "Restored!",
    restoreError: "Invalid file",
    availabilityMode: "Availability",
    selectUnavail: "Unavail",
    selectAvail: "Avail",
    cloudSync: "Sync",
    syncKey: "Sync Key",
    pushCloud: "Push Cloud",
    pullCloud: "Pull Cloud",
    syncSuccess: "Synced!",
    syncError: "Sync Failed (Check Key)",
    syncPlaceholder: "Agent Code",
    syncWarning: "Local data will be overwritten.",
    supremeConsole: "SUPREME Workspace",
    publish: "Publish Roster",
    retract: "Retract",
    pushToAll: "Push to All Devices",
    saveMyTime: "Confirm & Submit My Time",
    syncDone: "Sync Done!",
    syncDoneMsg: "Updates live for everyone",
    supremeThinking: "SUPREME is arranging...",
    pleaseFillAvail: "Please fill availability",
    waitingSupreme: "Waiting for SUPREME to publish",
    finalizedMsg: "Roster Finalized",
    finalizedSub: "Please follow your assigned shifts",
    statusFinalized: "Published",
    statusDraft: "Drafting",
    vacant: "VACANT",
    logoutConfirm: "Log out?",
    syncingCloud: "Aligning Cloud Data...",
    syncingCloudSub: "LG Supreme Secure Sync",
    addPartner: "Add Partner",
    partnerList: "Partner List",
    submittedStatus: "Submitted",
    pendingStatus: "Pending",
    partnerName: "Name",
    partnerCode: "Code",
    resetStatus: "Reset Statuses",
    resetConfirm: "Reset all 'Submitted' flags? (Use for new month)",
    partnerAdded: "Partner Added",
    partnerDeleted: "Partner Deleted"
  },
  ms: {
    title: "LG Subscribe Supreme",
    partnerPortal: "Portal Rakan Kongsi",
    supremeSystem: "Sistem Pengurusan SUPREME",
    agentCodeLabel: "Kod Ejen",
    schedule: "Jadual Tugas",
    docCenter: "Dokumen",
    loginTitle: "Log Masuk Selamat",
    loginBtn: "Masuk Sistem",
    slot1: "Syif Pagi", 
    slot2: "Syif Petang",
    weekdays: ["Ahad", "Isnin", "Selasa", "Rabu", "Khamis", "Jumaat", "Sabtu"],
    memo: "Hebahan",
    forms: "Borang",
    upload: "Terbit",
    generate: "AI Jadual",
    deleteAgent: "Padam Ejen",
    confirmTitle: "Sahkan",
    peakDay: "Trafik",
    empty: "Kosong",
    get: "Dapatkan",
    adminConsole: "Admin SUPREME",
    personalSettings: "Ketersediaan",
    markUnavail: "Tanda tidak tersedia",
    confirmBtn: "Sahkan",
    backBtn: "Kembali",
    leads: "Lead",
    leadProtection: "Anti-Curi",
    registerLead: "Lead Baru",
    customerName: "Pelanggan",
    customerInfo: "ID Info",
    productInterest: "Produk",
    visitLocation: "Lokasi",
    visitDate: "Tarikh",
    submitLead: "Hantar",
    leadHistory: "Rekod",
    protectionActive: "Aktif",
    aiThinking: "Menganalisis...",
    noLeads: "Tiada rekod",
    reportAgent: "Ejen",
    expectedVisit: "Jangkaan",
    regDate: "Tarikh",
    quickGen: "Cepat",
    quickGenMsg: "Logik asas.",
    aiGenMsg: "AI optimum.",
    invalidLogin: "Gagal: Kod Salah",
    fillAllInfo: "Isi maklumat",
    confirmDeleteLead: "Batal lead?",
    leadSubmitted: "Berjaya!",
    enterAgentName: "Nama ejen:",
    enterAgentCode: "Kod ejen:",
    isPTConfirm: "Rakan Kongsi PT?",
    confirmDeleteAgent: "Padam ejen?",
    status: "Status",
    management: "Rakan Kongsi",
    exportData: "Eksport",
    importData: "Pulihkan",
    backupSuccess: "Selesai",
    restoreSuccess: "Berjaya!",
    restoreError: "Fail salah",
    availabilityMode: "Ketersediaan",
    selectUnavail: "Tidak Sedia",
    selectAvail: "Sedia",
    cloudSync: "Segerak",
    syncKey: "Kunci",
    pushCloud: "Hantar Awan",
    pullCloud: "Ambil Awan",
    syncSuccess: "Berjaya!",
    syncError: "Gagal Segerak",
    syncPlaceholder: "Kod Ejen",
    syncWarning: "Data tempatan akan diganti.",
    supremeConsole: "Meja Kerja SUPREME",
    publish: "Terbit Jadual",
    retract: "Tarik Balik",
    pushToAll: "Hantar ke Semua",
    saveMyTime: "Sahkan & Hantar",
    syncDone: "Selesai!",
    syncDoneMsg: "Kemas kini dihantar",
    supremeThinking: "SUPREME sedang menyusun...",
    pleaseFillAvail: "Sila isi ketersediaan",
    waitingSupreme: "Menunggu SUPREME terbit",
    finalizedMsg: "Jadual Selesai",
    finalizedSub: "Sila ikut syif yang ditetapkan",
    statusFinalized: "Diterbitkan",
    statusDraft: "Draf",
    vacant: "KOSONG",
    logoutConfirm: "Log keluar?",
    syncingCloud: "Menyegerak Data...",
    syncingCloudSub: "LG Supreme Secure Sync",
    addPartner: "Tambah Rakan",
    partnerList: "Senarai Rakan",
    submittedStatus: "Dihantar",
    pendingStatus: "Belum",
    partnerName: "Nama",
    partnerCode: "Kod",
    resetStatus: "Set Semula Status",
    resetConfirm: "Set semula semua status 'Dihantar'? (Guna untuk bulan baru)",
    partnerAdded: "Berjaya Tambah",
    partnerDeleted: "Berjaya Padam"
  }
};

export const LG_MAROON = "#A50034";
