
import React from 'react';

export const AGENT_COLORS = [
  { bg: 'bg-rose-500', text: 'text-white' },
  { bg: 'bg-sky-500', text: 'text-white' },
  { bg: 'bg-emerald-500', text: 'text-white' },
  { bg: 'bg-amber-500', text: 'text-white' },
  { bg: 'bg-violet-500', text: 'text-white' },
  { bg: 'bg-indigo-500', text: 'text-white' },
];

export const LANGUAGES = {
  zh: {
    title: "LG Subscribe Supreme",
    schedule: "排班表",
    docCenter: "管理 / 文檔",
    loginTitle: "系統安全登入",
    loginBtn: "進入系統",
    slot1: "早班 (10am-4pm)", 
    slot2: "晚班 (4pm-10pm)",
    weekdays: ["日", "一", "二", "三", "四", "五", "六"],
    memo: "重要公告 (Memo)",
    forms: "申請表格 (Forms)",
    upload: "發布文檔",
    generate: "AI 排班生成",
    deleteAgent: "刪除代理",
    confirmTitle: "操作確認",
    peakDay: "人流高峰",
    empty: "空缺",
    get: "獲取",
    adminConsole: "管理控制台",
    personalSettings: "個人可用性設定",
    markUnavail: "點擊標記不方便的時間",
    confirmBtn: "確認並執行",
    backBtn: "返回",
    leads: "顧客報備",
    leadProtection: "搶單防護系統",
    registerLead: "報備新顧客",
    customerName: "顧客稱呼",
    customerInfo: "辨識資訊 (如電話後4位)",
    productInterest: "意向產品 / 項目 (Mention Product)",
    visitLocation: "預計前往地點",
    visitDate: "預計日期",
    submitLead: "提交報備",
    leadHistory: "報備紀錄",
    protectionActive: "防護生效中",
    aiThinking: "正在分析報備紀錄、可用性及工作量。PT 限制已強制執行。",
    noLeads: "目前無報備紀錄",
    reportAgent: "報備代理",
    expectedVisit: "預計到訪",
    regDate: "登記日期 / 系統時間",
    quickGen: "快速生成",
    quickGenMsg: "根據基礎邏輯自動分配人手 (強制執行 PT 限制)。",
    aiGenMsg: "AI 將自動優化排班，確保人手充足並符合 PT 規定。",
    invalidLogin: "無效的密碼或代理代碼 (LSM123 或 M/F000000)",
    fillAllInfo: "請填寫完整資訊 (姓名、辨識碼及預計日期)",
    confirmDeleteLead: "確定要取消此報備紀錄嗎？",
    leadSubmitted: "報備成功！搶單防護已生效。",
    enterAgentName: "輸入代理姓名:",
    enterAgentCode: "輸入 Agent Code (M/F000000):",
    isPTConfirm: "是否為 Part-Time (PT) 員工？\n(取消則默認為 Full-Time FT)",
    confirmDeleteAgent: "確定要從系統中移除這位代理嗎？相關排班可能受影響。",
    status: "狀態",
    management: "管理"
  },
  en: {
    title: "LG Subscribe Supreme",
    schedule: "Duty Roster",
    docCenter: "Docs / Account",
    loginTitle: "Secure Portal Login",
    loginBtn: "Enter System",
    slot1: "AM Shift (10am-4pm)", 
    slot2: "PM Shift (4pm-10pm)",
    weekdays: ["Sun", "Mon", "Tue", "Wed", "Thu", "Fri", "Sat"],
    memo: "Important Memos",
    forms: "Application Forms",
    upload: "Publish Doc",
    generate: "AI Auto-Duty",
    deleteAgent: "Remove Agent",
    confirmTitle: "Confirm Action",
    peakDay: "Peak Traffic",
    empty: "Vacant",
    get: "Get",
    adminConsole: "Admin Console",
    personalSettings: "My Availability",
    markUnavail: "Click to mark unavailable slots",
    confirmBtn: "Confirm & Execute",
    backBtn: "Back",
    leads: "Leads Protection",
    leadProtection: "Lead Anti-Theft System",
    registerLead: "Register New Lead",
    customerName: "Customer Name",
    customerInfo: "ID Info (e.g. Last 4 Digits)",
    productInterest: "Interested Product / Item",
    visitLocation: "Target Location",
    visitDate: "Expected Date",
    submitLead: "Submit Lead",
    leadHistory: "Lead History",
    protectionActive: "Protection Active",
    aiThinking: "Analyzing leads, availability, and workload. PT limits strictly enforced.",
    noLeads: "No lead records found",
    reportAgent: "Assigned Agent",
    expectedVisit: "Expected Visit",
    regDate: "Registered Date / System Time",
    quickGen: "Quick Gen",
    quickGenMsg: "Auto-assign based on basic logic (Strict PT limits applied).",
    aiGenMsg: "AI will optimize roster to ensure enough manpower and PT compliance.",
    invalidLogin: "Invalid password or agent code (LSM123 or M/F000000)",
    fillAllInfo: "Please fill in all info (Name, ID Info, and Date)",
    confirmDeleteLead: "Are you sure you want to cancel this lead record?",
    leadSubmitted: "Lead registered! Protection is now active.",
    enterAgentName: "Enter agent name:",
    enterAgentCode: "Enter Agent Code (M/F000000):",
    isPTConfirm: "Is this a Part-Time (PT) employee?\n(Cancel for Full-Time FT)",
    confirmDeleteAgent: "Are you sure you want to remove this agent? Rosters may be affected.",
    status: "Status",
    management: "Management"
  },
  ms: {
    title: "LG Subscribe Supreme",
    schedule: "Jadual Tugas",
    docCenter: "Dokumen / Akaun",
    loginTitle: "Log Masuk Portal Selamat",
    loginBtn: "Masuk Sistem",
    slot1: "Syif Pagi (10am-4pm)", 
    slot2: "Syif Petang (4pm-10pm)",
    weekdays: ["Ahad", "Isnin", "Selasa", "Rabu", "Khamis", "Jumaat", "Sabtu"],
    memo: "Hebahan Penting",
    forms: "Borang Permohonan",
    upload: "Terbit Dokumen",
    generate: "Penjanan AI",
    deleteAgent: "Padam Ejen",
    confirmTitle: "Sahkan Tindakan",
    peakDay: "Trafik Tinggi",
    empty: "Kosong",
    get: "Dapatkan",
    adminConsole: "Konsol Admin",
    personalSettings: "Ketersediaan Saya",
    markUnavail: "Klik untuk tandakan slot tidak tersedia",
    confirmBtn: "Sahkan & Laksana",
    backBtn: "Kembali",
    leads: "Perlindungan Lead",
    leadProtection: "Sistem Anti-Curi Lead",
    registerLead: "Daftar Lead Baru",
    customerName: "Nama Pelanggan",
    customerInfo: "Maklumat ID (cth. 4 Digit Terakhir)",
    productInterest: "Produk Diminati",
    visitLocation: "Lokasi Sasaran",
    visitDate: "Tarikh Jangkaan",
    submitLead: "Hantar Lead",
    leadHistory: "Rekod Lead",
    protectionActive: "Perlindungan Aktif",
    aiThinking: "Menganalisis lead, ketersediaan, dan beban kerja. Had PT dikuatkuasakan.",
    noLeads: "Tiada rekod lead ditemui",
    reportAgent: "Ejen Bertanggungjawab",
    expectedVisit: "Jangkaan Lawatan",
    regDate: "Tarikh Daftar / Masa Sistem",
    quickGen: "Janana Cepat",
    quickGenMsg: "Tugas automatik berdasarkan logik asas (Had PT ketat).",
    aiGenMsg: "AI akan mengoptimumkan jadual untuk memastikan tenaga kerja mencukupi.",
    invalidLogin: "Kata laluan atau kod ejen tidak sah (LSM123 atau M/F000000)",
    fillAllInfo: "Sila isi semua maklumat (Nama, Maklumat ID, dan Tarikh)",
    confirmDeleteLead: "Adakah anda pasti mahu membatalkan rekod lead ini?",
    leadSubmitted: "Lead berjaya didaftar! Perlindungan kini aktif.",
    enterAgentName: "Masukkan nama ejen:",
    enterAgentCode: "Masukkan Kod Ejen (M/F000000):",
    isPTConfirm: "Adakah ini pekerja Sambilan (PT)?\n(Batal untuk Tetap FT)",
    confirmDeleteAgent: "Adakah anda pasti mahu memadam ejen ini? Jadual tugas mungkin terjejas.",
    status: "Status",
    management: "Pengurusan"
  }
};

export const LG_MAROON = "#A50034";
